from __future__ import annotations

import pytest

from gromacs_gui.gmx.topology import build_wrapping_topology, parse_moleculetype_name

SAMPLE_ITP = """; ligand.itp - generated by an external tool
[ moleculetype ]
; name  nrexcl
LIG          3

[ atoms ]
; nr  type  resnr  residue  atom  cgnr  charge
1     c3    1      LIG      C1    1     0.0
"""


def test_parse_moleculetype_name_reads_first_token(tmp_path):
    itp = tmp_path / "ligand.itp"
    itp.write_text(SAMPLE_ITP)

    assert parse_moleculetype_name(itp) == "LIG"


def test_parse_moleculetype_name_raises_without_section(tmp_path):
    itp = tmp_path / "bad.itp"
    itp.write_text("[ atoms ]\n1 c3 1 LIG C1 1 0.0\n")

    with pytest.raises(ValueError):
        parse_moleculetype_name(itp)


def test_build_wrapping_topology_includes_forcefield_and_itp():
    text = build_wrapping_topology("ligand.itp", "oplsaa", "LIG")

    assert '#include "oplsaa.ff/forcefield.itp"' in text
    assert '#include "ligand.itp"' in text
    assert "[ molecules ]" in text
    assert "LIG" in text.splitlines()[-1]
    assert text.splitlines()[-1].split()[-1] == "1"
