from __future__ import annotations

import pytest

from gromacs_gui.gmx.topology import (
    build_combined_topology,
    build_wrapping_topology,
    extract_generated_topology_chunk,
    parse_moleculetype_name,
    rename_moleculetype,
    rename_posre_include,
)

SAMPLE_ITP = """; ligand.itp - generated by an external tool
[ moleculetype ]
; name  nrexcl
LIG          3

[ atoms ]
; nr  type  resnr  residue  atom  cgnr  charge
1     c3    1      LIG      C1    1     0.0
"""

# Mirrors the real structure gmx pdb2gmx writes (verified against a real
# 2025.3 build): header comments, one force field #include, one or more
# [ moleculetype ] blocks, a posres #ifdef, then - unless -water none was
# used - a water model #include/#ifdef POSRES_WATER/ions #include block,
# and finally [ system ]/[ molecules ].
GENERATED_TOP_WITH_WATER = """;
;	File 'topol.top' was generated
;	By user: someone
;

; Include forcefield parameters
#include "amber99sb-ildn.ff/forcefield.itp"

[ moleculetype ]
; Name            nrexcl
Protein_chain_A     3

[ atoms ]
; nr type resnr residue atom cgnr charge mass
1  N3  1  LYS  N  1  0.0966  14.01

; Include Position restraint file
#ifdef POSRES
#include "posre.itp"
#endif

; Include water topology
#include "amber99sb-ildn.ff/tip3p.itp"

#ifdef POSRES_WATER
; Position restraint for each water oxygen
[ position_restraints ]
;  i funct       fcx        fcy        fcz
   1    1       1000       1000       1000
#endif

; Include topology for ions
#include "amber99sb-ildn.ff/ions.itp"

[ system ]
; Name
LYSOZYME

[ molecules ]
; Compound        #mols
Protein_chain_A     1
"""

GENERATED_TOP_NO_WATER = """;
; header comments
;

; Include forcefield parameters
#include "amber99sb-ildn.ff/forcefield.itp"

[ moleculetype ]
; Name            nrexcl
Protein_chain_A     3

[ atoms ]
1  N3  1  LYS  N  1  0.0966  14.01

; Include Position restraint file
#ifdef POSRES
#include "posre.itp"
#endif
"""


def test_parse_moleculetype_name_reads_first_token(tmp_path):
    itp = tmp_path / "ligand.itp"
    itp.write_text(SAMPLE_ITP)

    assert parse_moleculetype_name(itp) == "LIG"


def test_parse_moleculetype_name_raises_without_section(tmp_path):
    itp = tmp_path / "bad.itp"
    itp.write_text("[ atoms ]\n1 c3 1 LIG C1 1 0.0\n")

    with pytest.raises(ValueError):
        parse_moleculetype_name(itp)


def test_build_wrapping_topology_includes_forcefield_and_itp():
    text = build_wrapping_topology("ligand.itp", "oplsaa", "LIG")

    assert '#include "oplsaa.ff/forcefield.itp"' in text
    assert '#include "ligand.itp"' in text
    assert "[ molecules ]" in text
    assert "LIG" in text.splitlines()[-1]
    assert text.splitlines()[-1].split()[-1] == "1"


def test_extract_generated_topology_chunk_drops_header_and_forcefield_include(tmp_path):
    top = tmp_path / "topol.top"
    top.write_text(GENERATED_TOP_WITH_WATER)

    chunk = extract_generated_topology_chunk(top, include_water_and_ions=True)

    assert '#include "amber99sb-ildn.ff/forcefield.itp"' not in chunk
    assert "File 'topol.top' was generated" not in chunk
    assert chunk.startswith("[ moleculetype ]")


def test_extract_generated_topology_chunk_drops_system_and_molecules(tmp_path):
    top = tmp_path / "topol.top"
    top.write_text(GENERATED_TOP_WITH_WATER)

    chunk = extract_generated_topology_chunk(top, include_water_and_ions=True)

    assert "[ system ]" not in chunk
    assert "[ molecules ]" not in chunk
    assert "LYSOZYME" not in chunk


def test_extract_generated_topology_chunk_keeps_water_when_requested(tmp_path):
    top = tmp_path / "topol.top"
    top.write_text(GENERATED_TOP_WITH_WATER)

    chunk = extract_generated_topology_chunk(top, include_water_and_ions=True)

    assert '#include "amber99sb-ildn.ff/tip3p.itp"' in chunk
    assert '#include "amber99sb-ildn.ff/ions.itp"' in chunk


def test_extract_generated_topology_chunk_drops_water_when_not_requested(tmp_path):
    top = tmp_path / "topol.top"
    top.write_text(GENERATED_TOP_WITH_WATER)

    chunk = extract_generated_topology_chunk(top, include_water_and_ions=False)

    assert '#include "amber99sb-ildn.ff/tip3p.itp"' not in chunk
    assert '#include "amber99sb-ildn.ff/ions.itp"' not in chunk
    assert "#ifdef POSRES" in chunk  # the molecule's own posres block stays


def test_extract_generated_topology_chunk_handles_no_water_case(tmp_path):
    """When -water none was used, pdb2gmx doesn't even write [ system ]/
    [ molecules ] at all - the chunk should just be everything to EOF.
    """
    top = tmp_path / "topol.top"
    top.write_text(GENERATED_TOP_NO_WATER)

    chunk = extract_generated_topology_chunk(top, include_water_and_ions=True)

    assert chunk.startswith("[ moleculetype ]")
    assert "#ifdef POSRES" in chunk
    assert chunk.strip().endswith("#endif")


def test_extract_generated_topology_chunk_raises_without_moleculetype(tmp_path):
    top = tmp_path / "topol.top"
    top.write_text("; nothing useful here\n")

    with pytest.raises(ValueError):
        extract_generated_topology_chunk(top, include_water_and_ions=True)


def test_rename_moleculetype_preserves_nrexcl_and_comment():
    text = "[ moleculetype ]\n; Name            nrexcl\nProtein_chain_A     3\n\n[ atoms ]\n"

    renamed = rename_moleculetype(text, "Protein_chain_A_2")

    assert "Protein_chain_A_2     3" in renamed
    assert "; Name            nrexcl" in renamed
    assert renamed.count("Protein_chain_A") == 1  # the old name is fully gone


def test_rename_moleculetype_raises_without_section():
    with pytest.raises(ValueError):
        rename_moleculetype("[ atoms ]\n1 c3 1 LIG C1 1 0.0\n", "NEW")


def test_rename_posre_include_updates_only_the_matching_filename():
    text = '#ifdef POSRES\n#include "posre.itp"\n#endif\n'

    renamed = rename_posre_include(text, "posre.itp", "posre_mol2.itp")

    assert '#include "posre_mol2.itp"' in renamed
    assert '#include "posre.itp"' not in renamed


def test_build_combined_topology_lists_every_molecule_once():
    text = build_combined_topology(
        force_field_includes=['#include "amber99sb-ildn.ff/forcefield.itp"\n'],
        molecule_chunks=["[ moleculetype ]\nProtein_chain_A 3\n", '#include "lig.itp"\n'],
        molecules=[("Protein_chain_A", 1), ("LIG", 1)],
    )

    assert text.count("#include") == 2
    assert "[ system ]" in text
    assert "[ molecules ]" in text
    assert "Protein_chain_A 1" in text
    assert "LIG        1" in text
